local M = {}

local fmt = string.format

local lang_mappings = {
	lua = "nlua",
}

local function parse_style(style)
	if not style or style == "NONE" then
		return {}
	end

	if type(style) == "table" then
		return style
	end

	local result = {}
	for token in string.gmatch(style, "([^,]+)") do
		result[token] = true
	end

	return result
end

local function template(roles, groups, opts, hash)
	local lines = {
		"\tlocal hl = vim.api.nvim_set_hl",
		"\tif vim.g.colors_name then",
		'\t\tvim.cmd("hi clear")',
		"\tend\n",
		'\tvim.cmd("syntax reset")',
		"\tvim.o.termguicolors = true",
		'\tvim.g.colors_name = "autumn"',
		'\tvim.o.background = "dark"\n',
		"\t--- spec\n",
	}

	if opts.terminal_colors == true then
		local terminal = require("autumn.group.terminal").get(roles)
		for k, v in pairs(terminal) do
			table.insert(lines, "\t" .. fmt([[vim.g.%s = "%s"]], k, v))
		end
	end

	for group, attrs in pairs(groups) do
		if attrs.link and attrs.link ~= "" then
			table.insert(lines, "\t" .. fmt([[hl(0, "%s", { link = "%s" })]], group, attrs.link))
		else
			local style_str = attrs.style or attrs.gui or "NONE"

			local op = parse_style(style_str)
			op.bg = attrs.bg
			op.fg = attrs.fg
			op.sp = attrs.sp

			table.insert(lines, "\t" .. fmt([[hl(0, "%s", %s)]], group, vim.inspect(op)))
		end
	end

	return fmt(
		[[
--------------------------------
--- Generated by autumn.nvim ---
--------------------------------
return {
  hash = %q,
  code = string.dump(function()
%s
  end)
}]],
		hash,
		table.concat(lines, "\n")
	)
end

local function get_opts(opts)
	return type(opts) == "boolean" and { disable = not opts } or type(opts) == "table" and opts or {}
end

local function load_roles(opts)
	local p = require("autumn.palette")

	local roles = require("autumn.roles").get(p, opts.styles)
	roles = vim.tbl_deep_extend("force", roles, opts.overrides or {})

	roles.palette = p.palette

	return roles
end

local function load_groups(opts, roles)
	local editor = require("autumn.group.editor").get(roles, opts)
	local syntax = require("autumn.group.syntax").get(roles, opts)

	local built = vim.tbl_deep_extend("force", editor, syntax)

	for mod, mod_opts in pairs(opts.modules) do
		mod_opts = get_opts(mod_opts)
		if mod_opts.disable == false then
			local mod_hls = require("autumn.group.modules." .. mod).get(roles, opts, mod_opts)
			built = vim.tbl_deep_extend("force", built, mod_hls)
		end
	end

	for lang, lang_opts in pairs(opts.langs) do
		lang = lang_mappings[lang] or lang
		lang_opts = get_opts(lang_opts)
		if lang_opts.disable == false then
			local lang_hls = require("autumn.group.lang." .. lang).get(roles, opts, lang_opts)
			built = vim.tbl_deep_extend("force", built, lang_hls)
		end
	end

	return built
end

function M.get_hash(opts)
	local script_path = debug.getinfo(1).source:sub(2)
	local plugin_root = vim.fn.fnamemodify(script_path, ":h:h:h")

	local git_path = plugin_root .. "/.git/index"
	local git_mtime = vim.fn.getftime(git_path)

	if git_mtime == -1 then
		git_mtime = vim.fn.getftime(script_path)
	end

	local content = vim.inspect(opts) .. tostring(git_mtime)
	return vim.fn.sha256(content)
end

function M.compile(opts)
	opts = opts or {}

	local config = require("autumn.config")
	local files = require("autumn.files")

	local roles = load_roles()
	local groups = load_groups(config.options, roles)

	local output_path, output_file = config.get_compiled_info(opts)
	files.ensure_dir(output_path)

	local hash = opts.hash or M.get_hash(config.options)
	local scheme = template(roles, groups, config.options, hash)

	local isValid = loadstring(scheme)
	if not isValid then
		local logfile = vim.fn.stdpath("log") .. "/autumn.lua"
		vim.notify(fmt([[There is an error in your autumn config, refer to %s]], logfile))

		files.write_file(logfile, scheme)
		dofile(logfile)
	else
		files.write_file(output_file, scheme)
	end
end

return M
