local M = {}

function M.get(spec, _)
  local diag = spec.diag
  local diff = spec.diff
  local syn = spec.syntax
  
  return {
    ColorColumn = { bg = spec.bg2 },
    Conceal = { fg = spec.bg4 },
    Cursor = { fg = spec.bg1, bg = spec.fg1 },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    CursorColumn = { link = "CursorLine" },
    CursorLine = { bg = spec.bg3 },
    Directory = { fg = syn.func },
    DiffAdd = { bg = diff.add },
    DiffChange = { bg = diff.change },
    DiffDelete = { bg = diff.delete },
    DiffText = { bg = diff.text },
    EndOfBuffer = { fg = spec.bg1 },
    ErrorMsg = { fg = diag.error },
    WinSeparator = { fg = spec.bg0 },
    VertSplit = { link = "WinSeparator" },
    Folded = { fg = spec.fg3, bg = spec.bg2 },
    FoldColumn = { fg = spec.fg3 },
    SignColumn = { fg = spec.fg3 },
    SignColumnSB = { link = "SignColumn" },
    Substitute = { fg = spec.bg1, bg = diag.error },
    LineNr = { fg = spec.fg3 },
    CursorLineNr = { fg = diag.warn, style = "bold" },
    MatchParen = { fg = diag.warn, style = "bold" },
    ModeMsg = { fg = diag.warn, style = "bold" },
    MsgArea = { fg = spec.fg2 },
    MoreMsg = { fg = diag.info, style = "bold" },
    NonText = { fg = spec.bg4 },
    Normal = { fg = spec.fg1, bg = spec.bg1 },
    NormalNC = { fg = spec.fg1, bg = spec.bg1 },
    NormalFloat = { fg = spec.fg1, bg = spec.bg0 },
    FloatBorder = { fg = spec.fg3 },
    Pmenu = { bg = spec.bg2 },
    PmenuSel = { fg = spec.bg2, bg = spec.fg1, blend = 0 },
    PmenuSbar = { link = "Pmenu" },
    PmenuThumb = { bg = spec.bg3 },
    Question = { link = "MoreMsg" },
    QuickFixLine = { link = "CursorLine" },
    Search = { fg = spec.fg1, bg = spec.bg3 },
    IncSearch = { fg = spec.bg1, bg = diag.hint },
    CurSearch = { link = "IncSearch" },
    SpecialKey = { link = "NonText" },
    SpellBad = { sp = diag.error, style = "undercurl" },
    SpellCap = { sp = diag.warn, style = "undercurl" },
    SpellLocal = { sp = diag.info, style = "undercurl" },
    SpellRare = { sp = diag.info, style = "undercurl" },
    StatusLine = { fg = spec.fg2, bg = spec.bg0 },
    StatusLineNC = { fg = spec.fg3, bg = spec.bg0 },
    TabLine = { fg = spec.fg2, bg = spec.bg2 },
    TabLineFill = { bg = spec.bg0 },
    TabLineSel = { fg = spec.bg1, bg = spec.fg3 },
    Title = { fg = syn.func, style = "bold" },
    Visual = { bg = spec.bg2 },
    VisualNOS = { link = "Visual" },
    WarningMsg = { fg = diag.warn },
    Whitespace = { fg = spec.bg3 },
    WildMenu = { link = "Pmenu" },
    WinBar = { fg = spec.fg3, bg = spec.bg1, style = "bold" },
    WinBarNC = { fg = spec.fg3, bg = spec.bg1, style = "bold" },
  }
end

return M
