local M = {}

function M.get(spec, _)
	local diag = spec.diag
	local diff = spec.diff

	return {
		ColorColumn = { bg = spec.bg3 },
		Conceal = { link = "NonText" },
		Cursor = { fg = spec.bg1, bg = spec.fg1 },
		CursorColumn = { link = "CursorLine" },
		CursorIM = { link = "Cursor" },
		CursorLine = { bg = spec.bg2 },
		CursorLineNr = { fg = diag.warn, style = "bold" },
		CurSearch = { link = "IncSearch" },
		Directory = { fg = spec.p0 },
		DiffAdd = { bg = diff.add },
		DiffChange = { bg = diff.change },
		DiffDelete = { bg = diff.delete },
		DiffText = { bg = diff.text },
		EndOfBuffer = { fg = spec.bg1 },
		ErrorMsg = { fg = diag.error },
		FloatBorder = { fg = spec.fg3 },
		Folded = { fg = spec.fg3, bg = spec.bg2 },
		FoldColumn = { fg = spec.fg3 },
		IncSearch = { fg = spec.bg1, bg = diag.hint },
		LineNr = { fg = spec.fg3 },
		MatchParen = { fg = diag.warn, style = "bold" },
		ModeMsg = { fg = diag.ok, style = "bold" },
		MoreMsg = { fg = diag.info, style = "bold" },
		MsgArea = { fg = spec.fg2 },
		NonText = { fg = spec.bg3 },
		Normal = { fg = spec.fg1, bg = spec.bg1 },
		NormalFloat = { bg = spec.bg0 },
		NormalNC = { link = "Normal" },
		Pmenu = { bg = spec.bg2 },
		PmenuSbar = { link = "Pmenu" },
		PmenuSel = { fg = spec.bg2, bg = spec.fg1, blend = 0 },
		PmenuThumb = { bg = spec.bg3 },
		Question = { link = "MoreMsg" },
		QuickFixLine = { link = "CursorLine" },
		Search = { fg = spec.fg1, bg = spec.bg3 },
		SignColumn = { fg = spec.fg3 },
		SignColumnSB = { link = "SignColumn" },
		SpecialKey = { link = "NonText" },
		SpellBad = { sp = diag.error, style = "undercurl" },
		SpellCap = { sp = diag.warn, style = "undercurl" },
		SpellLocal = { sp = diag.info, style = "undercurl" },
		SpellRare = { sp = diag.info, style = "undercurl" },
		StatusLine = { fg = spec.bg2, bg = spec.fg2 },
		StatusLineNC = { fg = spec.fg2, bg = spec.bg2 },
		Substitute = { fg = spec.bg1, bg = diag.error },
		TabLine = { fg = spec.fg2, bg = spec.bg2 },
		TabLineFill = { bg = spec.bg0 },
		TabLineSel = { fg = spec.bg1, bg = spec.fg3 },
		Title = { fg = spec.fg1, style = "bold" },
		Visual = { bg = spec.bg3 },
		VisualNOS = { link = "Visual" },
		WarningMsg = { fg = diag.warn },
		Whitespace = { fg = spec.bg3 },
		WildMenu = { link = "Pmenu" },
		WinBar = { fg = spec.fg3, bg = spec.bg0, style = "bold" },
		WinBarNC = { fg = spec.fg3, bg = spec.bg0 },
		WinSeparator = { link = "Normal" },
		VertSplit = { link = "WinSeparator" },
		lCursor = { link = "Cursor" },
	}
end

return M
