local M = {}

local fmt = string.format

local function parse_style(style)
	if not style or style == "NONE" then
		return {}
	end

	local result = {}
	for token in string.gmatch(style, "([^,]+)") do
		result[token] = true
	end

	return result
end

local function inspect(tbl)
	local list = {}

	for k, v in pairs(tbl) do
		local q = type(v) == "string" and '"' or ""
		table.insert(list, fmt("%s = %s%s%s", k, q, v, q))
	end

	table.sort(list)
	return fmt([[{ %s }]], table.concat(list, ", "))
end

local function template(spec, groups, opts)
	local lines = {
		"--------------------------------",
		"--- Generated by autumn.nvim ---",
		"--------------------------------\n",
		"return string.dump(function()",
		"\tlocal hl = vim.api.nvim_set_hl",
		"\tif vim.g.colors_name then",
		'\t\tvim.cmd("hi clear")',
		"\tend\n",
		'\tvim.cmd("syntax reset")',
		"\tvim.o.termguicolors = true",
		'\tvim.o.colors_name = "autumn"',
		'\tvim.o.background = "dark"\n',
		"\t--- spec\n",
	}

	if opts.terminal_colors == true then
		local terminal = require("autumn.group.terminal").get(spec)
		for k, v in pairs(terminal) do
			table.insert(lines, "\t" .. fmt([[vim.g.%s = "%s"]], k, v))
		end
	end

	for group, attrs in pairs(groups) do
		if attrs.link and attrs.link ~= "" then
			table.insert(lines, "\t" .. fmt([[hl(0, "%s", { link = "%s" })]], group, attrs.link))
		else
			local op = parse_style(attrs)
			op.bg = attrs.bg
			op.fg = attrs.fg
			op.sp = attrs.sp

			table.insert(lines, "\t" .. fmt([[hl(0, "%s", %s)]], group, inspect(op)))
		end
	end

	table.insert(lines, "end)")

	return table.concat(lines, "\n")
end

local function deep_extend(...)
	local lhs = {}

	for _, rhs in ipairs({ ... }) do
		for k, v in pairs(rhs) do
			if type(lhs[k]) == "table" and type(v) == "table" then
				lhs[k] = deep_extend(lhs[k], v)
			else
				lhs[k] = v
			end
		end
	end
end

local function get_opts(opts)
	return type(opts) == "boolean" and { disable = not opts } or type(opts) == "table" and opts or {}
end

local function load_spec()
	local p = require("autumn.palette")
	local spec = p.generate_spec(p.palette)
	spec.palette = p.palette
	return spec
end

local function load_groups(cfg, spec)
	local editor = require("autumn.group.editor").get(spec, cfg.options)
	local syntax = require("autumn.group.syntax").get(spec, cfg.options)

	local built = deep_extend(editor, syntax)

	for mod, mod_opts in pairs(cfg.modules) do
		local opts = get_opts(mod_opts)
		if opts.disable == false then
			built = deep_extend(built, require("autumn.group.modules." .. mod).get(spec, cfg.options, opts))
		end
	end

	for lang, lang_opts in pairs(cfg.langs) do
		lang = cfg.lang_mappings[lang] or lang

		local opts = get_opts(lang_opts)
		if opts.disable == false then
			built = deep_extend(built, require("autumn.group.lang." .. lang).get(spec, cfg.options, opts))
		end
	end

	return built
end

function M.compile(opts)
	local config = require("autumn.config")
	local files = require("autumn.files")

	local spec = load_spec()
	local groups = load_groups(config, spec)

	local output_path, output_file = config.get_compiled_info(opts)
	files.ensure_dir(output_path)

	local scheme = template(spec, groups, config.options)

	local f = loadstring(scheme)
	if not f then
		local logfile = vim.fn.stdpath("log") .. "/autumn.lua"
		vim.notify(fmt([[There is an error in your autumn config, refer to %s]], logfile))

		files.write_file(logfile, scheme)
		dofile(logfile)
	else
		files.write_file(output_file, f())
	end
end

return M
