local M = {}

local function template(highlights)
	local lines = {
		"--- Generated by autumn.nvim",
		"local hl = vim.api.nvim_set_hl",
		"if vim.g.colors_name then",
		'\tvim.cmd("hi clear")',
		"end",
		'vim.cmd("syntax reset")',
		"vim.o.termguicolors = true",
		'vim.o.colors_name = "autumn"',
		'vim.o.background = "dark"',
	}

	for group, settings in pairs(highlights) do
		table.insert(lines, string.format('hl(0, "%s", %s)', group, vim.inspect(settings)))
	end

	return table.concat(lines, "\n")
end

function M.compile()
	local cache_path = vim.fn.stdpath("cache") .. "/autumn_compiled.lua"
	local file = io.open(cache_path, "w")
	file:write(template(hls))
	file:close()
end

return M
